config/routes.rb
V1::Application.routes.draw do

  devise_for :users
  resources :users

  resources :notes

  resources :batteries do
    resources :notes
  end
  
  resources :computers do
    resources :batteries
    resources :notes
  end

  get "pages/contact"
  get "pages/about"
  get "pages/software"
  get "pages/wifi"
  get "pages/passwords"
  get "pages/todo"
  get "home/index"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/software', :to => 'pages#software'
  match '/wifi', :to => 'pages#wifi'
  match '/passwords', :to => 'pages#passwords'
  match '/todo', :to => 'pages#todo'

  match '/computers/search', :controller => 'computers', :action => 'search'
  match '/batteries/search', :controller => 'batteries', :action => 'search'

  root :to => 'home#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
# Relationship
  belongs_to :computer
  belongs_to :battery

# User Accessable Fields
attr_accessible :user_name, :note_text, :computer_id, :battery_id

# Validation Rules
  validates :user_name, :presence => true, :length => { :maximum => 30 }
  validates :note_text, :presence => true, :length => { :maximum => 1000 }

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, :notice => 'Note was successfully created.' }
        format.json { render :json => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.json { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, :notice => 'Note was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/.#show.html.erb
Alex@The-Online-MBA.local.465

app/views/notes/_battery_notes.html.erb
<div id="note-area">
  <p></p>
  <% note_count = @battery.notes.count  %>
  <!--  <p><%= link_to_function("View Notes (#{note_count})", "Element.toggle('notes')") %></p> -->
  <!--   <div id="notes" style="display:none;"> --> 
  <div id="notes">
    <h1><%= "Notes (#{note_count})" %></h1>
    <hr>
    <% @battery.notes.each do |note| %>
    <p>
      <b>By:</b>
      <%= note.user_name %>
    </p>
    <p>
      <b>Note:</b>
      <%= note.note_text %>
    </p>
    <p>
      <b>Date:</b>
      <%= note.updated_at %>
    </p>
    <p>
      <!-- <p>  <%= link_to 'Delete Note', [note.battery, note], :confirm => 'Are you sure?', :method => :delete %></p> -->
      <hr>
      <% end %>
  </div> <!-- id="note" -->
</div> <!-- id="note-area" -->

app/views/notes/_computer_notes.html.erb
<div id="note-area">
  <p></p>
  <% note_count = @computer.notes.count  %>
  <!--  <p><%= link_to_function("View Notes (#{note_count})", "Element.toggle('notes')") %></p> -->
  <!--   <div id="notes" style="display:none;"> --> 
  <div id="notes">
    <h1><%= "Notes (#{note_count})" %></h1>
    <hr>
    <% @computer.notes.each do |note| %>
    <p>
      <b>By:</b>
      <%= note.user_name %>
    </p>
    <p>
      <b>Note:</b>
      <%= note.note_text %>
    </p>
    <p>
      <b>Date:</b>
      <%= note.updated_at %>
    </p>
    <p>
      <!-- <p>  <%= link_to 'Delete Note', [note.computer, note], :confirm => 'Are you sure?', :method => :delete %></p> -->
      <hr>
      <% end %>
  </div> <!-- id="note" -->
</div> <!-- id="note-area" -->

app/views/notes/_form.html.erb
<%= form_for(@note, :html => { :class=>"yform"}) do |f| %>
<% if @note.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>
 <ul>
    <% @note.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<fieldset class="columnar">
  <legend>Note Details</legend>
  
  <div class="type-text">
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>
  <div class="type-text">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>
  <div class="type-text">
    <%= f.label :note_text %>
    <%= f.text_area :note_text %>
  </div>
  <div class="type-text">
    <%= f.label :computer_id %>
    <%= f.text_field :computer_id %>
  </div>
  <div class="type-text">
    <%= f.label :battery_id %>
    <%= f.text_field :battery_id %>
  </div>
  <div class="type-button">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/notes/_note.html.erb
<tr onclick="location.href='<%= note_path(note.id) %>'">
  <td><%= note.updated_at.to_formatted_s(:long) %></td>
  <td><%= note.user_name %></td>
  <td><%= note.note_text %></td>
  <!-- <p>  <%= link_to 'Delete Note', [note.computer, note], :confirm => 'Are you sure?', :method => :delete %></p> -->
</tr>

app/views/notes/edit.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "note.jpg", :size => "80x80" %>
    <br \> 
    <div class="info">
      <!-- add your content here -->
      <p><%= link_to 'Show Note', @note %></p>
      <p><%= link_to 'Note List', notes_path %></p>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">
    <div class="subcolumns">
      <div class="c80l">
	<div class="subcl">
	  <h3>Edit Note Details</h3>
	  <%= render 'form' %>
	</div>
      </div>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "note.jpg", :size => "80x80" %>
    <br \> 
  <div class="info">
      <!-- add your content here -->
      <p><strong>Filter</strong></p>
      <p><%= link_to "All", :filter => "All" %></p> 
      <p><%= link_to "Battery", :filter => "battery" %></p>
      <p><%= link_to "Computer", :filter => "computer" %></p>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">

<h1>Notes</h1>


<!-- <table cellpadding="5" cellspacing="0" border="1" class="pretty"> -->
<table class="full" class="pretty">
  <caption style="text-align:left"><%= @notes.count %> Notes in this view.</caption>
  <thead>
    <tr>
      <th scope="col" colspan="7">
	<br />
     </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Date</th>
      <th>User</th>
<!--      <th>User</th> -->
      <th>Note text</th>
      <th>Computer</th>
      <th>Battery</th>
      <th>Actions</th>
    </tr>

    <% @notes.each do |note| %>
    <tr valign="top" onclick="location.href='<%= note_path(note.id) %>'">
      <td><%= note.created_at.to_formatted_s(:long) %></td>
      <td><%= note.user_name %></td>
<!--      <td><%= note.user_id %></td> -->
      <td><%= note.note_text %></td>
      <td><%= note.computer.computer_jbbp_id rescue nil %></td>
      <td><%= note.battery.battery_jbbp_id rescue nil %></td>
      <td class="list-actions">
	<%= link_to 'Show', note %> | 
	<%= link_to 'Edit', edit_note_path(note) %> | 
	<%= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
    <% end %> <!-- @notes.each -->
    </tbody>
</table>

</div>
</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "note.jpg", :size => "80x80" %>
    <br \> 
  <div class="info">
      <!-- add your content here -->
      <p><%= link_to 'Edit Note', edit_note_path(@note) %></p>
      <p><%= link_to 'Note List', notes_path %></p>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">
    <div class="subcolumns">
      <div class="c80l">
	<div class="subcl">
	  <!--    <p id="notice"><%= notice %></p> -->

	  <table class="full" class="pretty">
	    <caption style="text-align:left">Note</caption>
	    <tbody>	  
	      <tr>
		<th scope="col" colspan="2"x>
		  Created By: <%= @note.user_name %>
		</th>
	      </tr>
	      <tr>
		<td><b>Created At:</b></td>
		<td><%= @note.created_at.to_formatted_s(:long) %></td>
	      </tr>
	      <tr>
		<td><b>Last Updated:</b></td>
		<td><%= @note.updated_at.to_formatted_s(:long) %></td>
	      </tr>
	      <tr>
		<td><b>Note text:</b></td>
		<td><%= @note.note_text %></td>
	      </tr>
	      <% if !@note.computer_id.nil?  %>
	      <tr onclick="location.href='<%= computer_path(@note.computer.id) %>'">
		<td><b>Computer:</b></td>
		<td><%= @note.computer.computer_jbbp_id rescue nil %></td>
		<% else %>
	      <tr onclick="location.href='<%= battery_path(@note.battery.id) %>'">
		<td><b>Battery:</b></td>
		<td><%= @note.battery.battery_jbbp_id rescue nil%></td>
		<% end %>
	      </tr>
	    </tbody>
	  </table>
	</div> <!-- class="subcolumns" -->
      </div> <!-- class="c50l" -->

      <div class="c20r">
	<div class="subcr">
	</div> <!-- class="subcr" -->
      </div> <!-- class="c50r" -->
    </div> <!-- class="subcolumns" -->

  </div>
</div>