config/routes.rb
V1::Application.routes.draw do

  devise_for :users
  resources :users

  resources :notes

  resources :batteries do
    resources :notes
  end
  
  resources :computers do
    resources :batteries
    resources :notes
  end

  get "pages/contact"
  get "pages/about"
  get "pages/software"
  get "pages/wifi"
  get "pages/passwords"
  get "pages/todo"
  get "home/index"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/software', :to => 'pages#software'
  match '/wifi', :to => 'pages#wifi'
  match '/passwords', :to => 'pages#passwords'
  match '/todo', :to => 'pages#todo'

  match '/computers/search', :controller => 'computers', :action => 'search'
  match '/batteries/search', :controller => 'batteries', :action => 'search'

  root :to => 'home#index'

end

app/models/computer.rb
class Computer < ActiveRecord::Base
# Relationship
  has_many :batteries, :dependent => :nullify 
  has_many :notes, :dependent => :delete_all

  # User Accessable Fields
  attr_accessible :computer_name_en, :computer_name_jp, :computer_model, :computer_serial_number, :computer_jbbp_id, :computer_os_version, :computer_memory, :computer_year_acquired, :computer_warrenty_expires, :computer_status

# Validation Rules
  validates :computer_name_en, :presence => true, :uniqueness => :true
  validates :computer_serial_number, :presence => true, :uniqueness => :true,
  :format => { :with => /[A-Z0-9]{2}-[A-Z0-9]{6}-[A-Z0-9]{3}/, 
    :message => "Format should be XX-XXXXXX-XXX" }
  validates :computer_jbbp_id, :presence => true, :uniqueness => :true


# Scope Settings
  scope :good, where(:computer_status => 'Good')
  scope :minor_issues, where(:computer_status => 'Minor Issues')
  scope :not_working, where(:computer_status => 'Not Working')
  scope :retired, where(:computer_status => 'Retired')
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction

  # GET /computers
  # GET /computers.json
  def index
    if  !params[:filter].nil? && params[:filter] != "All"
      @filtered_computers = Computer.where("computer_status = ?", params[:filter])
      @computers = @filtered_computers.order(sort_column + ' ' + sort_direction)
    else
      @computers = Computer.order(sort_column + ' ' + sort_direction)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @computers }
    end
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
    @computer = Computer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @computer }
    end
  end

  # GET /computers/new
  # GET /computers/new.json
  def new
    @computer = Computer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @computer }
    end
  end

  # GET /computers/1/edit
  def edit
    @computer = Computer.find(params[:id])
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(params[:computer])

    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, :notice => 'Computer was successfully created.' }
        format.json { render :json => @computer, :status => :created, :location => @computer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @computer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /computers/1
  # PUT /computers/1.json
  def update
    @computer = Computer.find(params[:id])

    respond_to do |format|
      if @computer.update_attributes(params[:computer])
        format.html { redirect_to @computer, :notice => 'Computer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @computer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer = Computer.find(params[:id])
    @computer.destroy
    
    respond_to do |format|      format.html { redirect_to computers_url }
      format.json { head :ok }
    end
  end

  # SEARCH /computers/search
  def search
    if params[:q]
      @query='%'+params[:q]+'%'
      @computers = Computer.where("computer_name_en LIKE ? OR computer_name_jp LIKE ? OR computer_jbbp_id LIKE ? OR computer_serial_number LIKE ?", @query, @query, @query ,@query)
    else
      @computers = []
    end
  end

  private

  def sort_column  
    Computer.column_names.include?(params[:sort]) ? params[:sort] : "computer_name_en"  
  end  
    
  def sort_direction  
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"  
  end 

end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_add_computer_note.html.erb
<!-- <p><%= link_to_function("Click to Add New Note",  "Element.toggle('add-note')") %></p> -->
<div id="add-note"> <!-- style="display:none;"> -->


  <%= form_for([@computer, @computer.notes.build], :html => { :class=>"yform"}) do |f| %>

  <fieldset class="columnar">
    <legend>Add a Note</legend>
    
    <div class="type-text">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, :value => current_user.name %>
    </div>
    <div class="type-text">
      <%= f.label :note_text %>
      <%= f.text_area :note_text %>
    </div>
    <div class="type-text">
      <%= f.label :computer_id %>
      <%= f.text_field :computer_id %>
    </div>
    <div class="type-button">
      <%= f.submit %>
    </div>
  </fieldset>
  <% end %>
</div> <!-- id="add-note" -->
  

app/views/computers/_form.html.erb
<%= form_for(@computer,:html => { :class=>"yform"}) do |f| %>
<% if @computer.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@computer.errors.count, "error") %> prohibited this computer from being saved:</h2>
  <ul>
    <% @computer.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<fieldset class="columnar">
  <legend>Computer Information</legend>
  
  <div class="type-text">
  <%= f.label :computer_name_en %> 
    <%= f.text_field :computer_name_en %>
  </div>
  <div class="type-text">
    <%= f.label :computer_name_jp %>
    <%= f.text_field :computer_name_jp %>
  </div>
  <div class="type-text">
    <%= f.label :computer_jbbp_id %>
    <%= f.text_field :computer_jbbp_id %>
  </div>
  <div class="type-select">
    <%= f.label :computer_model %>
    <%= f.select :computer_model, [
	['iBook G3 - 12in','iBook G3 - 12in'],
	['iBook G4 - 12in','iBook G4 - 12in'],
	['PowerBook G4','iPowerBook G4'],
	['MacBook - 4.2','MacBook - 4.2'],
	['MacBook - 4.3','MacBook - 4.3'],
	['MacBook - 5.2','MacBook - 5.2'],
	['MacBook - 6.1','MacBook - 6.1'],
	['Other','Other']] %>
  </div>
  <div class="type-select">
    <%= f.label 'OS Version' %>
    <%= f.select :computer_os_version, [
	['Mac OS X - 10.2.8','Mac OS X - 10.2.8'],
	['Mac OS X - 10.2.8','Mac OS X - 10.2.8'],
	['Mac OS X - 10.3','Mac OS X - 10.3'],
	['Mac OS X - 10.3.9','Mac OS X - 10.3.9'],
	['Mac OS X - 10.4','Mac OS X - 10.4'],
	['Mac OS X - 10.5','Mac OS X - 10.5'], 
	['Mac OS X - 10.5.6','Mac OS X - 10.5.6'], 
	['Mac OS X - 10.6','Mac OS X - 10.6'], 
	['Mac OS X - 10.6.4','Mac OS X - 10.6.4'], 
	['Mac OS X - 10.7','Mac OS X - 10.7'],
	['Other','Other']] %>
  </div>
  <div class="type-text"x>
    <%= f.label 'Memory' %>
    <%= f.number_field :computer_memory %>
  </div>
  <div class="type-text">
    <%= f.label 'Serial Number' %>
    <%= f.text_field :computer_serial_number %>
  </div>
  <div class="type-text">
    <%= f.label 'Purchase Date' %>
    <%= f.date_select :computer_year_acquired %>
  </div>
  <div class="type-text">
    <%= f.label 'Warranty Expires' %>
    <%= f.date_select :computer_warrenty_expires %>
  </div>
  <div class="type-select">
    <%= f.label 'Status' %>x
    <%= f.select :computer_status, [['Good','Good'],['Minor Issues','Minor Issues'],['Not Working','Not Working'],['Retired','Retired']] %>
  </div>
  <div class="type-button">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/computers/_list_computers.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "ibook.jpg", :size => "80x80" %>
  <br \> 
 <div class="info">
      <!-- add your content here -->
      <p><strong>Filter: </strong></p>
      <p><%= link_to "All", :filter => "All" %></p>
      <p><%= link_to "Good", :filter => "Good" %></p> 
      <p><%= link_to "Minor Issues", :filter => "Minor Issues" %></p> 
      <p><%= link_to "Not Working", :filter => "Not Working" %></p> 
      <p><%= link_to "Retired", :filter => "Retired" %></p>
      <hr \>      
      <p><strong>Actions:</strong></p>
      <%= link_to 'New Computer', new_computer_path %>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">


<h1>Computers</h1>

<!-- <p> <%= link_to "Toggle View<tbd>", :view => "detailed" %></p> -->

<table class="full" class="pretty">
 <caption style="text-align:left"><%= @computers.count %> Computers in this view.</caption>
  <thead>
    <tr>
      <th scope="col" colspan="9">
	<%= form_tag(:controller => "computers", :action => "search", :method => "get") do %>
	<%= label_tag(:q, "Search for:") %>
	<%= text_field_tag(:q) %>
	<%= submit_tag("Search") %>
	<% end %>
    </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th colspan="5">Computer Information</th>
      <th colspan="2">Battery Information</th>
      <th rowspan="2">Actions</th>
    </tr>
    <tr>
      <th><%= sortable "computer_jbbp_id", "JBBP ID" %></th>
      <th><%= sortable "computer_name_en", "Name (English)" %></th>
      <th><%= sortable "computer_name_jp", "Name (Japanese)" %></th>
      <th><%= sortable "computer_model", "Model" %></th>
      <th><%= sortable "computer_status", "Computer Status" %></th>
      <th>JBBP ID</th>
      <th>Battery Status</th>
   </tr>
    <% for computer in @computers %>
    <tr onclick="location.href='<%= computer_path(computer.id) %>'">
     <td><%= computer.computer_jbbp_id %></td>
      <td><%= computer.computer_name_en %></td>
      <td><%= computer.computer_name_jp %></td>
      <td><%= computer.computer_model %></td>
      <td><strong><%= format_status computer.computer_status %></strong></td>
      <td><%= create_battery_link computer.id %></td>
      <td><strong><%= format_status get_battery_status computer.id %></strong></td>
      <td class="list-actions">
	<%= link_to 'Show', computer %> |
	<%= link_to 'Edit', edit_computer_path(computer) %> |
	<%= link_to 'Delete', computer, :confirm => 'Are you sure?',
	:method => :delete %>
      </td>
    </tr>
    <% end %>
      </tbody>
  </table>
</div>
</div>

app/views/computers/edit.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "ibook.jpg", :size => "80x80" %>
    <br \> 
    <div class="info">
      <!-- add your content here -->
      <p><%= link_to 'Show Computer', @computer %></p>
      <p><%= link_to 'Computer List', computers_path %></p>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">
    <h3>Edit Computer</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/computers/index.html.erb
<%= render "list_computers" %>

app/views/computers/new.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "ibook.jpg", :size => "80x80" %>
    <br \> 
    <div class="info">
      <!-- add your content here -->
      <p><%= link_to 'Computer List', computers_path %><p>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">
    <h3>Create New Computer</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/computers/search.html.erb
 <%= render "list_computers" %>

app/views/computers/show.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "ibook.jpg", :size => "80x80" %>
    <br \> 
    <div class="info">
      <!-- add your content here -->
      <p><%= link_to 'Edit Computer', edit_computer_path(@computer) %></p>
      <p><%= link_to 'New Computer', new_computer_path %></p>
      <p><%= link_to 'Back to Computers', computers_path %></p>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">
    <div class="subcolumns">
      <div class="c38l">
	<div class="subcl">
	  <!-- Insert your subtemplate content here -->
	  <table class="full" class="pretty">
	    <caption style="text-align:left">Computer Details</caption>
	    <tbody>	  
	      <tr>
		<th>
		  <%= @computer.computer_name_en %>
		</th>
		<th>
		  <%= @computer.computer_jbbp_id %>
		</th>
	      </tr>
	      <tr>
		<td>Name (Japanese):</td>
		<td><%= @computer.computer_name_jp %></td>
	      </tr>
	      <tr>
		<td>JLIP ID:</td>
		<td><%= @computer.computer_jbbp_id %></td>
	      </tr>
	      <tr>
		<td>Model:</td>
		<td><%= @computer.computer_model %></td>
	      </tr>
	      <tr>
		<td>OS Version:</td>
		<td><%= @computer.computer_os_version %></td>
	      </tr>
	      <tr>
		<td>Serial Number:</td>
		<td><%= @computer.computer_serial_number %></td>
	      </tr>
	      <tr>
		<td>Memory:</td>
		<td><%= @computer.computer_memory %></td>
	      </tr>
	      <tr>
		<td>Purchase Date:</td>
		<td><%= @computer.computer_year_acquired %></td>
	      </tr>
	      <tr>
		<td>Warrenty Expires:</td>
		<td><%= @computer.computer_warrenty_expires %></td>
	      </tr>
	      <tr>
		<td>Status:</td>
		<td><%= @computer.computer_status %></td>
	      </tr>
	    </tbody>
	  </table>
	  
	  <%= render @computer.batteries %>
	  
	  <%  unless !@computer.batteries.empty? %>
	  
	  <h2>No Battery Present </h2>
	  
	  <p><%= link_to_function('Click to add a battery', "Element.toggle('add-battery')") %></p>
	  
	  <div id="add-battery" style="display:none;">
	    
	    <%= form_for([@computer, @computer.batteries.build], :html => {:class=>"yform"}) do |f| %>
	    <fieldset class="columnar">
	      <legend>Add New Battery</legend>
	      
	      <div class="type-text">
		<%= f.label :battery_jbbp_id %>
		<%= f.text_field :battery_jbbp_id %>
	      </div>
	      <div class="type-text">
		<%= f.label :battery_model %>
		<%= f.text_field :battery_model %>
	      </div>
	      <div class="type-text">
		<%= f.label :battery_serial_number %>
		<%= f.text_field :battery_serial_number %>
	      </div>
	      <div class="type-select">
		<%= f.label :battery_status %>
		<%= f.select :battery_status, [['Good','Good'],['Weak','Weak'],['Not Working','Not Working'],['Retired','Retired']] %>
	      </div>
	      <div class="type-text">
		<%= f.label :computer_id %>
		<%= f.text_field :computer_id %>
	      </div>
	      <div class="type-button">
		<%= f.submit %>
	      </div>
	  </fieldset>
	  <% end %> <!-- form_for -->

	  <h3>Add an existing battery - NOT WORKING - DO NOT USE </h3>
	  
	  <form>
	    <%= select("battery", "computer_id", 
		Battery.where(:computer_id => nil).map {|battery| [battery.battery_jbbp_id, battery.id] }) %>,
	    <input type="submit" value="Add Battery" />
	  </form>


	</div> <!-- id="add-battery" -->
	<% end %> <!-- unless battery is empty -->


      </div> <!-- class="subcolumns" -->
    </div> <!-- class="c50l" -->

    <div class="c62r">
      <div class="subcr">
	<table class="full">
	  <caption style="text-align:left">Notes (<%= @computer.notes.count %>)</caption>
	  <tbody>
	    <tr>
	      <th>Date</th>
	      <th>Name</th>
	      <th>Note</th>
	    </tr>
	    <%= render @computer.notes %>
	  </tbody>
	</table>
	<%= render "add_computer_note" %>
      </div> <!-- class="subcr" -->
    </div> <!-- class="c50r" -->
  </div> <!-- class="subcolumns" -->
</div>
</div>