config/routes.rb
V1::Application.routes.draw do

  devise_for :users
  resources :users

  resources :notes

  resources :batteries do
    resources :notes
  end
  
  resources :computers do
    resources :batteries
    resources :notes
  end

  get "pages/contact"
  get "pages/about"
  get "pages/software"
  get "pages/wifi"
  get "pages/passwords"
  get "pages/todo"
  get "home/index"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/software', :to => 'pages#software'
  match '/wifi', :to => 'pages#wifi'
  match '/passwords', :to => 'pages#passwords'
  match '/todo', :to => 'pages#todo'

  match '/computers/search', :controller => 'computers', :action => 'search'
  match '/batteries/search', :controller => 'batteries', :action => 'search'

  root :to => 'home#index'

end

app/models/battery.rb
class Battery < ActiveRecord::Base
# Relationship
  belongs_to :computer
  has_many :notes, :dependent => :delete_all

# User Accessable Fields
attr_accessible :battery_serial_number, :battery_jbbp_id, :battery_model, :battery_status, :computer_id

# Validation Rules
  validates :battery_serial_number, :presence => true, :uniqueness => :true
  validates :battery_jbbp_id, :presence => true, :uniqueness => :true
  validates :computer_id, :uniqueness => :true, :unless => "computer_id==0 || computer_id==nil"

# Scope Settings
  scope :good, where(:battery_status => 'Good')
  scope :weak, where(:battery_status => 'Weak')
  scope :not_working, where(:battery_status => 'Not Working')
  scope :retired, where(:battery_status => 'Retired')
end

app/controllers/batteries_controller.rb
class BatteriesController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  # GET /batteries
  # GET /batteries.json
  def index
    if  !params[:filter].nil? && params[:filter] != "All"
      @filtered_batteries = Battery.where("battery_status = ?", params[:filter])
      @batteries = @filtered_batteries.order(sort_column + ' ' + sort_direction)
    else
      @batteries = Battery.order(sort_column + ' ' + sort_direction)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @batteries }
    end
  end

  # GET /batteries/1
  # GET /batteries/1.json
  def show
    @battery = Battery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @battery }
    end
  end

  # GET /batteries/new
  # GET /batteries/new.json
  def new
    @battery = Battery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @battery }
    end
  end

  # GET /batteries/1/edit
  def edit
    @battery = Battery.find(params[:id])
  end

  # POST /batteries
  # POST /batteries.json
  def create
    @battery = Battery.new(params[:battery])

    respond_to do |format|
      if @battery.save
        format.html { redirect_to @battery, :notice => 'Battery was successfully created.' }
        format.json { render :json => @battery, :status => :created, :location => @battery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @battery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /batteries/1
  # PUT /batteries/1.json
  def update
    @battery = Battery.find(params[:id])

    respond_to do |format|
      if @battery.update_attributes(params[:battery])
        format.html { redirect_to @battery, :notice => 'Battery was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @battery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /batteries/1
  # DELETE /batteries/1.json
  def destroy
    @battery = Battery.find(params[:id])
    @battery.destroy

    respond_to do |format|
      format.html { redirect_to batteries_url }
      format.json { head :ok }
    end
  end

  # SEARCH /batteries/search
  def search
    if params[:q]
      @query='%'+params[:q]+'%'
      @batteries = Battery.where("battery_jbbp_id LIKE ? OR battery_serial_number LIKE ? OR battery_model LIKE ?", @query, @query, @query)
    else
      @computers = []
    end
  end

  private

  def sort_column  
    Battery.column_names.include?(params[:sort]) ? params[:sort] : "battery_jbbp_id"  
  end  
    
  def sort_direction  
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"   

  end 


end

app/helpers/batteries_helper.rb
module BatteriesHelper
end

app/views/batteries/_add_battery_note.html.erb
<!--<p><%= link_to_function('Click to Add New Note', "Element.toggle('add-note')") %></p> -->

<div id="add-note"> <!-- style="display:none;"> -->

  <%= form_for([@battery, @battery.notes.build], :html => { :class=>"yform"}) do |f| %>

  <fieldset class="columnar">
    <legend>Add a Note</legend>
    
    <div class="type-text">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, :value => current_user.name %>
    </div>
    <div class="type-text">
      <%= f.label :note_text %>
      <%= f.text_area :note_text %>
    </div>
   <div class="type-text">
      <%= f.label :battery_id %>
      <%= f.text_field :battery_id %>
    </div>
    <div class="type-button">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>
</div> <!-- id="add-note"  -->

app/views/batteries/_battery.html.erb
<table class="full" class="pretty">
  <caption style="text-align:left">Battery Details</caption>
  <tbody>
    <tr onclick="location.href='<%= battery_path(battery.id) %>'">
      <td><b>JBBP ID:</b></td>
      <td><%= link_to battery.battery_jbbp_id, battery %></td>
   </tr>
    <tr>
      <td><b>Model:</b></td>
      <td><%= battery.battery_model %></td>
    </tr>
    <tr>
      <td><b>Serial Number:</b></td>
      <td><%= battery.battery_serial_number %></td>
    </tr>
    <tr>
      <td><b>Battery status:</b></td>
      <td><%= battery.battery_status %></td>
    </tr>
    <tr>
      <td><b>Belongs to Computer:</b></td>
      <td><%= battery.computer.computer_name_en %></td>
    </tr>
  </tbody>
</table>

<p>
  <%= link_to 'Remove this battery from computer', 
      battery_path(battery.id, 
      :battery => { :computer_id => 'nil'}),
      :confirm => 'Are you sure you want to remove this battery from this computer?',
      :method => :put 
  %>
</p>

app/views/batteries/_form.html.erb
<%= form_for(@battery, :html => {:class=>"yform"}) do |f| %>
<% if @battery.errors.any? %>
<div id="error_explanation" class="warning">
  <h2><%= pluralize(@battery.errors.count, "error") %> prohibited this battery from being saved:</h2>
  <ul>
    <% @battery.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<fieldset class="columnar">
  <legend>Battery Information</legend>
 
<div class="type-text">
  <%= f.label :battery_jbbp_id %>
    <%= f.text_field :battery_jbbp_id %>
  </div>
  <div class="type-text">
    <%= f.label :battery_model %>
    <%= f.text_field :battery_model %>
  </div>
  <div class="type-text">
    <%= f.label :battery_serial_number %>
    <%= f.text_field :battery_serial_number %>
  </div>
  <div class="type-select">
    <%= f.label :battery_status %>
    <%= f.select :battery_status, [['Good','Good'],['Weak','Weak'],['Not Working','Not Working'],['Retired','Retired']] %>
  </div>
  <div class="type-select">
    <%= f.label :computer_id %>
    <!--   <%= @battery_list = Battery.where("computer_id = nil") %> -->
    <%= @computer_list = Computer.find(:all, :order => "computer_name_en")
    collection_select(:battery, :computer_id, @computer_list, :id, :computer_name_en, {:prompt => true, :include_blank => '<Remove>'})
      %>
  </div>

  <div class="type-button">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/batteries/_list_batteries.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "battery.jpg", :size => "85x85" %>
    <br \> 
    <div class="info">
      <!-- add your content here -->
      <p><strong>Filter: </strong></p>
      <p><%= link_to "All", :filter => "All" %></p>
      <p><%= link_to "Good", :filter => "Good" %></p> 
      <p><%= link_to "Weak", :filter => "Weak" %></p> 
      <p><%= link_to "Not Working", :filter => "Not Working" %></p> 
      <p><%= link_to "Retired", :filter => "Retired" %></p> 
      <hr \>
      <p><strong>Actions:</strong></p>
      <%= link_to 'New Battery', new_battery_path %>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">

<h1>Batteries</h1>

<table class="full" class="pretty">
  <caption style="text-align:left"><%= @batteries.count %> Batteries in this view.</caption>
  <thead>
    <tr>
      <th scope="col" colspan="6">
	<%= form_tag(:controller => "batteries", :action => "search", :method => "get") do %>
	<%= label_tag(:q, "Search for:") %>
	<%= text_field_tag(:q) %>
	<%= submit_tag("Search") %>
	<% end %>
    </th>
    </tr>
  </thead>
 <tbody>
    <tr>
      <th><%= sortable  "battery_jbbp_id", "JLIP ID" %></th>
      <th><%= sortable "battery_model", "Model" %></th>
      <th><%= sortable "battery_serial_number", "Serial Number "%></th>
      <th><%= sortable "battery_status", "Status" %></th>
      <th>Belongs to Computer</th>
      <th>Actions</th>
    </tr>

    <% @batteries.each do |battery| %>
    <tr onclick="location.href='<%= battery_path(battery.id) %>'">
      <td><%= battery.battery_jbbp_id %></td>
      <td><%= battery.battery_model %></td>
      <td><%= battery.battery_serial_number %></td>
      <td><b><%= format_status battery.battery_status %></b></td>
      <td>
	<%= create_computer_link(battery.computer_id) %>
      </td>
      <td class="list-actions"><%= link_to 'Show', battery %> | 
	<%= link_to 'Edit', edit_battery_path(battery) %> | 
	<%= link_to 'Delete', battery, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
    <% end %>
    </tbody>
</table>

</div>
</div>

app/views/batteries/edit.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "battery.jpg", :size => "80x80" %>
    <br \> 
  <div class="info">
      <!-- add your content here -->
      <p><%= link_to 'Show Battery', @battery %></p>
      <p><%= link_to 'Battery List', battery_path %></p>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">
    <h3>Edit Battery</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/batteries/index.html.erb
<h1>Batteries</h1>

<table class="full" class="pretty">
  <caption style="text-align:left"><%= @batteries.count %> Batteries in this view.</caption>
  <thead>
    <tr>
      <th scope="col" colspan="6">
	<p><strong> Filter: </strong>
	  <%= link_to "All", :filter => "All" %> | 
	  <%= link_to "Good", :filter => "Good" %> | 
	  <%= link_to "Weak", :filter => "Weak" %> | 
	  <%= link_to "Not Working", :filter => "Not Working" %> | 
	  <%= link_to "Retired", :filter => "Retired" %>
	</p>
      </th>
    </tr>
  </thead>
 <tbody>
    <tr>
      <th><%= sortable  "battery_jbbp_id", "JLIP ID" %></th>
      <th><%= sortable "battery_model", "Model" %></th>
      <th><%= sortable "battery_serial_number", "Serial Number "%></th>
      <th><%= sortable "battery_status", "Status" %></th>
      <th>Belongs to Computer</th>
      <th>Actions</th>
    </tr>

    <% @batteries.each do |battery| %>
    <tr>
      <td><%= battery.battery_jbbp_id %></td>
      <td><%= battery.battery_model %></td>
      <td><%= battery.battery_serial_number %></td>
      <td><b><%= format_status battery.battery_status %></b></td>
      <td>
	<%= create_computer_link(battery.computer_id) %>
      </td>
      <td class="list-actions"><%= link_to 'Show', battery %> | 
	<%= link_to 'Edit', edit_battery_path(battery) %> | 
	<%= link_to 'Delete', battery, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
    <% end %>
    </tbody>
</table>

<br />

<%= link_to 'New Battery', new_battery_path %>

app/views/batteries/new.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "battery.jpg", :size => "80x80" %>
    <br \> 
    <div class="info">
      <!-- add your content here -->
      <p><%= link_to 'Battery List', batteries_path %></p>
    </div>
  </div>
</div>
<div id="col3">
  <div id="col3_content" class="clearfix">
    <h3>Create New Battery</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/batteries/search.html.erb
<%= render "list_batteries" %>

app/views/batteries/show.html.erb
<div id="col1">
  <div id="col1_content" class="clearfix">
    <%= image_tag "battery.jpg", :size => "80x80" %>
    <br \> 
    <div class="info">
      <!-- add your content here -->
      <p><%= link_to 'Edit Battery', edit_battery_path(@battery) %></p>
      <p><%= link_to 'New Battery', new_battery_path %></p>
      <p><%= link_to 'Battery List', batteries_path %></p>
    </div><!-- class = "info" -->
  </div><!-- class="col1-content" -->
</div><!-- class="col1" -->
<div id="col3">
  <div id="col3_content" class="clearfix">
   <div class="subcolumns">
      <div class="c40l">
	<div class="subcl">
	  <!-- Insert your subtemplate content here -->
	  <table class="full" class="pretty">
	    <caption style="text-align:left">Battery Details</caption>
	    <tbody>	  
	      <tr>
		<th scope="col" colspan="2"  style="text-align:center">
		  <%= @battery.battery_jbbp_id %>
		</th>
	      </tr>
	      <tr>
		<td><b>JLIP ID:</b></td>
		<td><%= @battery.battery_jbbp_id %></td>
	      </tr>
	      <tr>
		<td><b>Model:</b></td>
		<td><%= @battery.battery_model %></td>
	      </tr>
	      <tr>
		<td><b>Serial Number:</b></td>
		<td><%= @battery.battery_serial_number %></td>
	      </tr>
	      <tr>
		<td><b>Battery status:</b></td>
		<td><%= @battery.battery_status %></td>
	      </tr>
	      <% if !@battery.computer.nil? %>
	      <tr onclick="location.href='<%= computer_path(@battery.computer.id)  %>'" >
		<td><b>Belongs to Computer (JBBP ID):</b></td>
		<td>
		  <%= @battery.computer.computer_name_en %> (<%= @battery.computer.computer_jbbp_id %>)
		</td>
	      </tr>
	      <% else %>
	      <tr>
		<td><b>Belongs to Computer (JBBP ID):</b></td>
		<td>none</td>
	      </tr>
	      <% end %>
	    </tbody>
	  </table>
	</div> <!-- class="subcl" -->
      </div> <!-- class="c..l" -->
      <div class="c60r">
	<div class="subcr">
	  <!-- Insert your subtemplate content here -->
	  <table class="full">
	    <caption style="text-align:left">Notes (<%= @battery.notes.count %>)</caption>
	    <tbody>
	      <tr>
		<th>Date</th>
		<th>Name</th>
		<th>Note</th>
	      </tr>
	      <%= render @battery.notes %>
	    </tbody>
	  </table>
	  <%= render "add_battery_note" %>
	</div> <!-- class="subcr" -->
      </div> <!-- class="c50r" -->
   </div> <!-- class="subcolumns" -->
  </div>
</div>