config/routes.rb
V1::Application.routes.draw do

  devise_for :users
  resources :users

  resources :notes

  resources :batteries do
    resources :notes
  end
  
  resources :computers do
    resources :batteries
    resources :notes
  end

  get "pages/contact"
  get "pages/about"
  get "pages/software"
  get "pages/wifi"
  get "pages/passwords"
  get "pages/todo"
  get "home/index"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/software', :to => 'pages#software'
  match '/wifi', :to => 'pages#wifi'
  match '/passwords', :to => 'pages#passwords'
  match '/todo', :to => 'pages#todo'

  match '/computers/search', :controller => 'computers', :action => 'search'
  match '/batteries/search', :controller => 'batteries', :action => 'search'

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title>
  <%= title %> <%= controller %> <%= controller.action_name %>
</title>

<!-- add your meta tags here -->
<%= stylesheet_link_tag "css/my_layout" %>
<!--[if lte IE 7]>
<%= stylesheet_link_tag "css/patches/patch_my_layout" %>
<![endif]-->

<%= javascript_include_tag "application" %>

<%= csrf_meta_tags %>
</head>
<body>
  <div class="page_margins">
    <!-- start: skip link navigation -->
    <!-- end: skip link navigation -->
    <div id="border-top">
      <div id="edge-tl"></div>
      <div id="edge-tr"></div>
    </div>
    <div class="page">
      <div id="header">
        <div id="topnav">
          <!-- start: skip link navigation -->
          <a class="skip" title="skip link" href="#navigation">Skip to the navigation</a><span class="hideme">.</span>
          <a class="skip" title="skip link" href="#content">Skip to the content</a><span class="hideme">.</span>
          <!-- end: skip link navigation -->
	  <div id="user_auth">
	    <% if user_signed_in? %>
	      <b>Welcome <%= current_user.name %></b><br \>
	         <%= link_to("Account Settings",edit_user_registration_path) %> |  
	         <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	    <% else %>
	      <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Login", new_user_session_path %>
	    <% end %>
	  </div> 
	</div>
	<div class="floatbox">
	  <%= image_tag "jbbp-masterhead.jpg",{:class => "center", :alt => "", :role => "presentation"} %>
	  <h1 class="center" role="presentation">Macintosh Database</h1>
	</div>
      </div>
      <div id="nav">
        <!-- skiplink anchor: navigation -->
        <a id="navigation" name="navigation"></a>
        <div class="hlist">
          <!-- main navigation: horizontal list -->
          <ul>
            <li><%= link_to 'Home', root_path %></li>
	    <% if user_signed_in? %>
	    <li><%= link_to 'Computers', computers_path %></li>
            <li><%= link_to 'Batteries', batteries_path %></li>
	    <li><%= link_to 'Software', software_path %></li>
	    <li><%= link_to 'WiFi', wifi_path %></li>
	    <li><%= link_to 'Passwords', passwords_path %></li>
	    <li><%= link_to 'Todo', todo_path %></li>
	    <% end %>
        </ul>
        </div>
      </div>
      <div id="main">
	<%= notice ?  content_tag(:p, notice, :class => "note")  : nil %>
	<%= alert ?  content_tag(:p, alert, :class => "warning") : nil %>
	<%= yield %>
      </div> <!-- "main" -->
      <!-- begin: #footer -->
      <div id="footer">
      <%= link_to 'Contact', contact_path %> |
      <%= link_to 'About', about_path %>
     </div> <!-- "footer" -->
    </div>
    <div id="border-bottom">
      <div id="edge-bl"></div>
      <div id="edge-br"></div>
    </div>
  </div>
</body>
</html>